version: '3'

services:

    algalog_database:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        env_file:
            - algalog_database.env
        
    algalog_app:
        build: .
        restart: always
        ports:
            - 8080:8080
        env_file:
            - algalog_app.env